### ISSUE TITLE
同主板使用EFI卡EB

### ISSUE THREAD

**Issue by wuxushun** [i886/JGINYUE-X99M-PLUS-D3-Hackintosh#1]
库主你好，非常感谢你的EFI。我使用你的EFI进入13.2.1安装程序卡EB，bios已关闭相应选项，请问有碰到过相关问题吗？
CPU：2666V3
内存：32G x 4
显卡：560x

**Comment by pymoni** [comment]
是V4.1的主板吗，如果是同型号那不应该，卡EB的问题已经解决了

**Comment by wuxushun** [comment]
你好，我的是老版本的plus d3。

**Comment by pymoni** [comment]
那需要重新提取SSDT，你可以去搜一下SSDTTime这个工具怎么用，提取完了替换一下就不会卡EB了，IRQ冲突的问题，老版本可能USB也需要重新定制

**Comment by wuxushun** [comment]
好的，感谢。我去看一下

**Comment by wuxushun** [comment]
生成ssdt hpet替换同文件后依然卡eb。方便加个微信不，有点迷茫。邮箱wuxushun@qq.com

**Comment by wuxushun** [comment]
![IMG_20230307_000837.jpg](https://user-images.githubusercontent.com/17354643/223461205-1a5536d2-64f6-4ab3-9e8e-75466efcff45.jpg)
目前卡在这里

**Comment by pymoni** [comment]
稍后联系你，注意下邮件
